/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppDispatchRouteImport } from './routes/app.dispatch'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppParcelsRouteImport } from './routes/app.parcels'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppReceptionRouteImport } from './routes/app.reception'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalHistoryRouteImport } from './routes/portal.history'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalRegisterRouteImport } from './routes/portal.register'
import { Route as PortalSignInRouteImport } from './routes/portal.sign-in'
import { Route as PortalTrackRouteImport } from './routes/portal.track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppParcelsRoute = AppParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHistoryRoute = PortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSignInRoute = PortalSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTrackRoute = PortalTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/track': typeof TrackRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parcels': typeof AppParcelsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/support': typeof AppSupportRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/sign-in': typeof PortalSignInRoute
  '/portal/track': typeof PortalTrackRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parcels': typeof AppParcelsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/support': typeof AppSupportRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/sign-in': typeof PortalSignInRoute
  '/portal/track': typeof PortalTrackRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/track': typeof TrackRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parcels': typeof AppParcelsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/support': typeof AppSupportRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/sign-in': typeof PortalSignInRoute
  '/portal/track': typeof PortalTrackRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/join'
    | '/login'
    | '/portal'
    | '/track'
    | '/app/branches'
    | '/app/companies'
    | '/app/customers'
    | '/app/dispatch'
    | '/app/notifications'
    | '/app/parcels'
    | '/app/payments'
    | '/app/reception'
    | '/app/reports'
    | '/app/settings'
    | '/app/subscription'
    | '/app/support'
    | '/app/tracking'
    | '/app/users'
    | '/c/$slug'
    | '/portal/history'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/sign-in'
    | '/portal/track'
    | '/app/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/join'
    | '/login'
    | '/track'
    | '/app/branches'
    | '/app/companies'
    | '/app/customers'
    | '/app/dispatch'
    | '/app/notifications'
    | '/app/parcels'
    | '/app/payments'
    | '/app/reception'
    | '/app/reports'
    | '/app/settings'
    | '/app/subscription'
    | '/app/support'
    | '/app/tracking'
    | '/app/users'
    | '/c/$slug'
    | '/portal/history'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/sign-in'
    | '/portal/track'
    | '/app'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/join'
    | '/login'
    | '/portal'
    | '/track'
    | '/app/branches'
    | '/app/companies'
    | '/app/customers'
    | '/app/dispatch'
    | '/app/notifications'
    | '/app/parcels'
    | '/app/payments'
    | '/app/reception'
    | '/app/reports'
    | '/app/settings'
    | '/app/subscription'
    | '/app/support'
    | '/app/tracking'
    | '/app/users'
    | '/c/$slug'
    | '/portal/history'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/sign-in'
    | '/portal/track'
    | '/app/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  TrackRoute: typeof TrackRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcels': {
      id: '/app/parcels'
      path: '/parcels'
      fullPath: '/app/parcels'
      preLoaderRoute: typeof AppParcelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reception': {
      id: '/app/reception'
      path: '/reception'
      fullPath: '/app/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/history': {
      id: '/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof PortalHistoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/register': {
      id: '/portal/register'
      path: '/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sign-in': {
      id: '/portal/sign-in'
      path: '/sign-in'
      fullPath: '/portal/sign-in'
      preLoaderRoute: typeof PortalSignInRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/track': {
      id: '/portal/track'
      path: '/track'
      fullPath: '/portal/track'
      preLoaderRoute: typeof PortalTrackRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AppRouteChildren {
  AppBranchesRoute: typeof AppBranchesRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParcelsRoute: typeof AppParcelsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReceptionRoute: typeof AppReceptionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBranchesRoute: AppBranchesRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParcelsRoute: AppParcelsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReceptionRoute: AppReceptionRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSupportRoute: AppSupportRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalHistoryRoute: typeof PortalHistoryRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalSignInRoute: typeof PortalSignInRoute
  PortalTrackRoute: typeof PortalTrackRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalHistoryRoute: PortalHistoryRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalSignInRoute: PortalSignInRoute,
  PortalTrackRoute: PortalTrackRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  TrackRoute: TrackRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
